apiVersion: apps/v1
kind: Deploymentddddd
metadata:
  name: my-deployment
  namespace: team1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: team1
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
